"""Sandra's migration

Revision ID: 7ff6ae35f842
Revises: 
Create Date: 2025-05-27 16:51:34.231505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff6ae35f842'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('grade', sa.String(length=10), nullable=True))
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_column('students', 'enrolled_date')
    op.drop_column('students', 'email')
    op.drop_column('students', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('enrolled_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('students', 'grade')
    # ### end Alembic commands ###
